# Generated by Django 4.0.5 on 2022-06-16 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_order', models.IntegerField()),
                ('zakaz', models.TextField()),
                ('price_d', models.FloatField()),
                ('price_r', models.FloatField()),
                ('date', models.DateField()),
            ],
        ),
    ]
